Alter Table DT_BudgetExpenseSheets Add E281 INT
Alter Table DT_BudgetExpenseSheets Add E282 INT
Alter Table DT_BudgetExpenseSheets Add E283 INT
Alter Table DT_BudgetExpenseSheets Add E284 INT
Alter Table DT_BudgetExpenseSheets Add E290 INT
Alter Table DT_BudgetExpenseSheets Add E310 INT
Alter Table DT_BudgetExpenseSheets Add E320 INT
Alter Table DT_BudgetExpenseSheets Add E330 INT
Alter Table DT_BudgetExpenseSheets Add E340 INT
Alter Table DT_BudgetExpenseSheets Add E350 INT
Alter Table DT_BudgetExpenseSheets Add E541 INT
Alter Table DT_BudgetExpenseSheets Add E542 INT
Alter Table DT_BudgetExpenseSheets Add E543 INT
Alter Table DT_BudgetExpenseSheets Add E561 INT
Alter Table DT_BudgetExpenseSheets Add E562 INT
Alter Table DT_BudgetExpenseSheets Add E580 INT
Alter Table DT_BudgetExpenseSheets Add E591 INT
Alter Table DT_BudgetExpenseSheets Add E592 INT
Alter Table DT_BudgetExpenseSheets Add E593 INT
Alter Table DT_BudgetExpenseSheets Add E594 INT
Alter Table DT_BudgetExpenseSheets Add E595 INT