//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSMPS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FBudgetMain_dynamic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBudgetMain_dynamic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSMPS.FBudgetMain_dynamic", typeof(FBudgetMain_dynamic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point c1CommandHolder1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("c1CommandHolder1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15,1,0,0,0,85,Columns:0{Width:50;}	1{Width:40;Caption:&quot;Task&quot;;}	2{Width:40;Caption:&quot;Cat&quot;;}	3{Width:40;Caption:&quot;Act&quot;;}	4{Caption:&quot;Sort1&quot;;Visible:False;}	5{Caption:&quot;Sort2&quot;;Visible:False;}	6{Caption:&quot;Sort3&quot;;Visible:False;}	7{Caption:&quot;EditType&quot;;Visible:False;}	8{Width:354;Caption:&quot;Description&quot;;}	9{Width:55;Caption:&quot;Quantity&quot;;}	10{Width:55;Caption:&quot;Hrs/Each&quot;;}	11{Width:65;Caption:&quot;Total Hours&quot;;}	12{Width:70;Caption:&quot;Loaded Rate&quot;;}	13{Width:70;Caption:&quot;Total Dollars&quot;;}	14{Caption:&quot;LineID&quot;;Visible:False;}	.
        /// </summary>
        public static string c1FlexGrid1_ColumnInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid1.ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal{Font:Microsoft Sans Serif, 8.25pt;}	Alternate{}	Fixed{BackColor:Control;ForeColor:ControlText;Border:Flat,1,ControlDark,Both;}	Highlight{BackColor:Highlight;ForeColor:HighlightText;}	Focus{}	Editor{}	Search{BackColor:Highlight;ForeColor:HighlightText;}	Frozen{BackColor:Beige;}	NewRow{}	EmptyArea{BackColor:AppWorkspace;Border:Flat,1,ControlDarkDark,Both;}	SelectedColumnHeader{}	SelectedRowHeader{}	GrandTotal{BackColor:Black;ForeColor:White;}	Subtotal0{BackColor:ControlDarkDark;ForeColor:White;}	Subtot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string c1FlexGrid1_StyleInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid1.StyleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9,1,0,0,0,85,Columns:0{Width:21;}	1{Width:60;Caption:&quot;Code&quot;;}	2{Width:50;Caption:&quot;Mkup&quot;;}	
        ///    3{Width:359;Caption:&quot;Description&quot;;}	4{Width:50;Caption:&quot;UOM&quot;;}	5{Width:65;Caption:&quot;$ Per Item&quot;;}	6{Width:65;Caption:&quot;# Items&quot;;}	
        ///    7{Width:90;Caption:&quot;Markup $&quot;;}	8{Width:90;Caption:&quot;Total $&quot;;}	.
        /// </summary>
        public static string c1FlexGrid2_ColumnInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid2.ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16,1,0,0,0,85,Columns:0{Width:50;}	1{Width:40;Caption:&quot;Task&quot;;AllowEditing:False;}	2{Width:40;Caption:&quot;Cat&quot;;AllowEditing:False;}	3{Width:40;Caption:&quot;Act&quot;;AllowEditing:False;}	4{Caption:&quot;Sort1&quot;;Visible:False;}	5{Caption:&quot;Sort2&quot;;Visible:False;}	6{Caption:&quot;Sort3&quot;;Visible:False;}	7{Caption:&quot;EditType&quot;;Visible:False;}	8{Width:354;Caption:&quot;Description&quot;;}	9{Width:55;Caption:&quot;Quantity&quot;;Style:&quot;DataType:System.Int32;TextAlign:RightCenter;&quot;;}	10{Width:55;Caption:&quot;Hrs/Each&quot;;Style:&quot;DataType:System.Int32;TextAlign:RightCen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string c1FlexGrid3_ColumnInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid3.ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal{Font:Microsoft Sans Serif, 8.25pt;}	Alternate{}	Fixed{BackColor:Control;ForeColor:ControlText;Border:Flat,1,ControlDark,Both;}	Highlight{BackColor:Highlight;ForeColor:HighlightText;}	Focus{}	Editor{}	Search{BackColor:Highlight;ForeColor:HighlightText;}	Frozen{BackColor:Beige;}	NewRow{}	EmptyArea{BackColor:AppWorkspace;Border:Flat,1,ControlDarkDark,Both;}	SelectedColumnHeader{}	SelectedRowHeader{}	GrandTotal{BackColor:Black;ForeColor:White;}	Subtotal0{BackColor:ControlDarkDark;ForeColor:White;}	Subtot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string c1FlexGrid3_StyleInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid3.StyleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11,1,0,0,0,85,Columns:0{Width:21;}	1{Width:60;Caption:&quot;Code&quot;;AllowDragging:False;AllowEditing:False;}	
        ///    2{Width:50;Caption:&quot;Mkup&quot;;AllowDragging:False;}	3{Width:359;Caption:&quot;Description&quot;;AllowDragging:False;AllowEditing:False;}	
        ///    4{Width:50;Caption:&quot;UOM&quot;;AllowDragging:False;}	5{Width:65;Caption:&quot;$ Per Item&quot;;AllowDragging:False;}	6{Width:65;Caption:&quot;# Items&quot;;AllowDragging:False;}	
        ///    7{Width:90;Caption:&quot;Markup $&quot;;AllowDragging:False;}	8{Width:90;Caption:&quot;Total $&quot;;AllowDragging:False;AllowEditing:Fal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string c1FlexGrid4_ColumnInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid4.ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal{Font:Microsoft Sans Serif, 8.25pt;}	Alternate{}	Fixed{BackColor:Control;ForeColor:ControlText;Border:Flat,1,ControlDark,Both;}	Highlight{BackColor:Highlight;ForeColor:HighlightText;}	Focus{}	Editor{}	Search{BackColor:Highlight;ForeColor:HighlightText;}	Frozen{BackColor:Beige;}	NewRow{}	EmptyArea{BackColor:AppWorkspace;Border:Flat,1,ControlDarkDark,Both;}	SelectedColumnHeader{}	SelectedRowHeader{}	GrandTotal{BackColor:Black;ForeColor:White;}	Subtotal0{BackColor:ControlDarkDark;ForeColor:White;}	Subtot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string c1FlexGrid4_StyleInfo {
            get {
                return ResourceManager.GetString("c1FlexGrid4.StyleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=758,Y=17}.
        /// </summary>
        public static System.Drawing.Point c1XLBook1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("c1XLBook1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=407,Y=17}.
        /// </summary>
        public static System.Drawing.Point cmnuBudget_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("cmnuBudget.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=169,Y=17}.
        /// </summary>
        public static System.Drawing.Point contextMenuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=613,Y=17}.
        /// </summary>
        public static System.Drawing.Point directorySearcher1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("directorySearcher1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16,1,0,0,0,85,Columns:0{Width:50;Name:&quot;Utility1&quot;;}	1{Width:50;Name:&quot;Task&quot;;Caption:&quot;Task&quot;;AllowEditing:False;}	2{Width:50;Name:&quot;Cat&quot;;Caption:&quot;Cat&quot;;AllowEditing:False;}	3{Width:50;Name:&quot;Act&quot;;Caption:&quot;Act&quot;;AllowEditing:False;}	4{Name:&quot;Sort1&quot;;Caption:&quot;Sort1&quot;;Visible:False;}	5{Name:&quot;Sort2&quot;;Caption:&quot;Sort2&quot;;Visible:False;}	6{Name:&quot;Sort3&quot;;Caption:&quot;Sort3&quot;;Visible:False;}	7{Name:&quot;EditType&quot;;Caption:&quot;EditType&quot;;Visible:False;}	8{Width:30;Name:&quot;WBS&quot;;Caption:&quot;WBS&quot;;}	9{Width:354;Name:&quot;Description&quot;;Caption:&quot;Description&quot;;}	1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fg_ColumnInfo {
            get {
                return ResourceManager.GetString("fg.ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal{Font:Microsoft Sans Serif, 8.25pt;}	Alternate{}	Fixed{BackColor:Control;ForeColor:ControlText;Border:Flat,1,ControlDark,Both;}	Highlight{BackColor:Highlight;ForeColor:HighlightText;}	Focus{}	Editor{}	Search{BackColor:Highlight;ForeColor:HighlightText;}	Frozen{BackColor:Beige;}	NewRow{}	EmptyArea{BackColor:AppWorkspace;Border:Flat,1,ControlDarkDark,Both;}	SelectedColumnHeader{}	SelectedRowHeader{}	GrandTotal{BackColor:Black;ForeColor:White;}	Subtotal0{BackColor:ControlDarkDark;ForeColor:White;}	Subtot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fg_StyleInfo {
            get {
                return ResourceManager.GetString("fg.StyleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11,1,0,0,0,85,Columns:0{Width:21;}	
        ///    1{Width:60;Caption:&quot;Code&quot;;AllowDragging:False;AllowEditing:False;}	2{Width:50;Caption:&quot;Mkup&quot;;AllowDragging:False;}	
        ///    3{Width:359;Caption:&quot;Description&quot;;AllowDragging:False;AllowEditing:False;}	4{Width:50;Caption:&quot;UOM&quot;;AllowDragging:False;Style:&quot;ComboList:&quot;&quot;Hour|Each|Lot&quot;&quot;;&quot;;}
        ///    5{Width:65;Caption:&quot;$ Per Item&quot;;AllowDragging:False;}	6{Width:65;Caption:&quot;# Items&quot;;AllowDragging:False;}	7{Width:90;Caption:&quot;Markup $&quot;;AllowDragging:False;}	
        ///    8{Width:90;Caption:&quot;Tot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fgExp_ColumnInfo {
            get {
                return ResourceManager.GetString("fgExp.ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal{Font:Microsoft Sans Serif, 8.25pt;}	Alternate{}	Fixed{BackColor:Control;ForeColor:ControlText;Border:Flat,1,ControlDark,Both;}	Highlight{BackColor:Highlight;ForeColor:HighlightText;}	Focus{}	Editor{}	Search{BackColor:Highlight;ForeColor:HighlightText;}	Frozen{BackColor:Beige;}	NewRow{}	EmptyArea{BackColor:AppWorkspace;Border:Flat,1,ControlDarkDark,Both;}	SelectedColumnHeader{}	SelectedRowHeader{}	GrandTotal{BackColor:Black;ForeColor:White;}	Subtotal0{BackColor:ControlDarkDark;ForeColor:White;}	Subtot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fgExp_StyleInfo {
            get {
                return ResourceManager.GetString("fgExp.StyleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=864,Y=17}.
        /// </summary>
        public static System.Drawing.Point saveFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("saveFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tdbdPCNStatus_Images {
            get {
                object obj = ResourceManager.GetObject("tdbdPCNStatus.Images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;Blob&gt;&lt;DataCols&gt;&lt;C1DataColumn Caption=&quot;Status&quot; DataField=&quot;Status&quot; SortDirection=&quot;Ascending&quot;&gt;&lt;FilterCancelText&gt;&amp;amp;Close&lt;/FilterCancelText&gt;&lt;FilterClearText&gt;C&amp;amp;lear&lt;/FilterClearText&gt;&lt;ValueItems /&gt;&lt;GroupInfo /&gt;&lt;/C1DataColumn&gt;&lt;C1DataColumn Caption=&quot;ID&quot; DataField=&quot;ID&quot;&gt;&lt;FilterCancelText&gt;&amp;amp;Close&lt;/FilterCancelText&gt;&lt;FilterClearText&gt;C&amp;amp;lear&lt;/FilterClearText&gt;&lt;ValueItems /&gt;&lt;GroupInfo /&gt;&lt;/C1DataColumn&gt;&lt;C1DataColumn Caption=&quot;Description&quot; DataField=&quot;Description&quot;&gt;&lt;FilterCancelText&gt;&amp;amp;Close&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tdbdPCNStatus_PropBag {
            get {
                return ResourceManager.GetString("tdbdPCNStatus.PropBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tdbgBudgetPCN_Images {
            get {
                object obj = ResourceManager.GetObject("tdbgBudgetPCN.Images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Printing.PageSettings similar to [PageSettings: Color=True, Landscape=False, Margins=[Margins Left=100 Right=100 Top=100 Bottom=100], PaperSize=[PaperSize Letter (8.5 x 11&quot;) Kind=Letter Height=1100 Width=850], PaperSource=[PaperSource Automatically Select Kind=FormSource], PrinterResolution=[PrinterResolution X=600 Y=600]].
        /// </summary>
        public static System.Drawing.Printing.PageSettings tdbgBudgetPCN_PrintInfo_PageSettings {
            get {
                object obj = ResourceManager.GetObject("tdbgBudgetPCN.PrintInfo.PageSettings", resourceCulture);
                return ((System.Drawing.Printing.PageSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;Blob&gt;&lt;DataCols&gt;&lt;C1DataColumn Caption=&quot;Status&quot; DataField=&quot;PCNStatus&quot; DropDownCtl=&quot;tdbdPCNStatus&quot;&gt;&lt;FilterCancelText&gt;&amp;amp;Close&lt;/FilterCancelText&gt;&lt;FilterClearText&gt;C&amp;amp;lear&lt;/FilterClearText&gt;&lt;ValueItems&gt;&lt;internalValues&gt;&lt;ValueItem type=&quot;C1.Win.C1TrueDBGrid.ValueItem&quot; Value=&quot;Pending&quot; /&gt;&lt;ValueItem type=&quot;C1.Win.C1TrueDBGrid.ValueItem&quot; Value=&quot;Out for Approval&quot; /&gt;&lt;ValueItem type=&quot;C1.Win.C1TrueDBGrid.ValueItem&quot; Value=&quot;Denied&quot; /&gt;&lt;ValueItem type=&quot;C1.Win.C1TrueDBGrid.ValueItem&quot; Value=&quot;Approved&quot; /&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tdbgBudgetPCN_PropBag {
            get {
                return ResourceManager.GetString("tdbgBudgetPCN.PropBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbBudgetEntry_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbBudgetEntry.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbBudgetExport_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbBudgetExport.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbExit_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbExit.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbJobStat_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbJobStat.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbMakeActive_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbMakeActive.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbMakeDefault_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbMakeDefault.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbNewRev_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbNewRev.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbPreviewDetails_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbPreviewDetails.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbPrintAll_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbPrintAll.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbSaveRev_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbSaveRev.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbSummary_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbSummary.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tlbbWorksheet_Icon {
            get {
                object obj = ResourceManager.GetObject("tlbbWorksheet.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=314,Y=17}.
        /// </summary>
        public static System.Drawing.Point tmrLoad_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tmrLoad.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=521,Y=17}.
        /// </summary>
        public static System.Drawing.Point toolTip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
